language: r
sudo: false
cache: packages
warnings_are_errors: true

r:
  - oldrel
  - release
  - devel

after_success:
  - Rscript -e 'covr::codecov()'

secure:
  "auH9vehj7OMqodPC1CZ92DsubAzNFi+TxDGVbAlbZQ6w0uwco2PeW/xa0K5a/xsSOGoUtpkU6uD27YxJatIyTez8TNd/r5BXplhrx2rwGlTfgXPG0SWSNYZOAfwiS21CVfwZfGSUD7tfQ+2gpRJKFDqGHVcfkJSxxuGQUfUlhb4="
